"""Deterministic test generation and bounded verification for Python projects."""
from __future__ import annotations

import ast
import json
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from .sandbox import run_process, safe_path

GENERATED_MARKER = "# GENERATED BY YASIN CODER TESTGEN; DO NOT EDIT."
DEFAULT_TIMEOUT = 60
MAX_TIMEOUT = 600


@dataclass(frozen=True)
class SourceUnit:
    path: Path
    module: str
    functions: tuple[str, ...] = ()
    classes: tuple[str, ...] = ()

    def as_dict(self) -> dict[str, object]:
        return {
            "path": str(self.path),
            "module": self.module,
            "functions": list(self.functions),
            "classes": list(self.classes),
        }


@dataclass
class GenerationReport:
    supported: bool
    language: str
    framework: str
    sources: list[SourceUnit] = field(default_factory=list)
    generated: list[Path] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, object]:
        return {
            "supported": self.supported,
            "language": self.language,
            "framework": self.framework,
            "sources": [s.as_dict() for s in self.sources],
            "generated": [str(p) for p in self.generated],
            "skipped": list(self.skipped),
        }


class TestGenerationError(ValueError):
    """Raised for invalid project or generation requests."""


def detect_framework(root: Path) -> tuple[str, str]:
    """Detect the project language/framework without importing project code."""
    if root.joinpath("pyproject.toml").is_file() or root.joinpath("setup.py").is_file() or any(root.glob("requirements*.txt")):
        try:
            has_pytest = any("pytest" in p.read_text(encoding="utf-8").lower() for p in root.glob("requirements*.txt"))
            if has_pytest:
                return "python", "pytest"
        except OSError:
            pass
        return "python", "unittest"
    if any(root.glob("*.py")):
        return "python", "unittest"
    if any(root.glob("*.js")) or any(root.glob("*.ts")):
        return "javascript", "unsupported"
    return "unknown", "unsupported"


def _module_name(root: Path, path: Path) -> str:
    relative = path.relative_to(root).with_suffix("")
    return ".".join(relative.parts)


def analyze_python_file(root: Path, path: Path) -> SourceUnit:
    path = safe_path(path, root)
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))
    functions: list[str] = []
    classes: list[str] = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            functions.append(node.name)
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
    return SourceUnit(path, _module_name(root, path), tuple(functions), tuple(classes))


def discover_sources(root: Path, changed_only: bool = False, base_ref: str = "HEAD^") -> list[SourceUnit]:
    """Find Python sources while excluding tests, generated files and build artifacts."""
    root = root.resolve()
    candidates: Iterable[Path]
    if changed_only:
        try:
            output = subprocess.check_output(
                ["git", "diff", "--name-only", base_ref, "--", "*.py"],
                cwd=root,
                text=True,
            )
            candidates = (root / line.strip() for line in output.splitlines() if line.strip())
        except (OSError, subprocess.CalledProcessError):
            candidates = root.rglob("*.py")
    else:
        candidates = root.rglob("*.py")
    result: list[SourceUnit] = []
    for path in sorted(candidates):
        try:
            relative = path.relative_to(root)
        except ValueError:
            continue
        if any(part in {".git", "build", "dist", "__pycache__", "generated"} for part in relative.parts):
            continue
        if "tests" in relative.parts or not path.is_file():
            continue
        try:
            result.append(analyze_python_file(root, path))
        except (OSError, UnicodeDecodeError, SyntaxError):
            continue
    return result


def _test_name(source: SourceUnit) -> str:
    return "test_" + source.module.replace(".", "_")


def render_test(root: Path, source: SourceUnit) -> str:
    """Render source-contract tests that never invent runtime behavior."""
    expected_functions = json.dumps(list(source.functions), ensure_ascii=True)
    expected_classes = json.dumps(list(source.classes), ensure_ascii=True)
    relative = source.path.relative_to(root).as_posix()
    return f'''{GENERATED_MARKER}
"""Generated structural contract tests for {source.module}."""
import ast
from pathlib import Path
import unittest

SOURCE = Path(__file__).parents[2] / {relative!r}
EXPECTED_FUNCTIONS = {expected_functions}
EXPECTED_CLASSES = {expected_classes}


class GeneratedContractTest(unittest.TestCase):
    def test_source_is_valid_python(self):
        tree = ast.parse(SOURCE.read_text(encoding="utf-8"), filename=str(SOURCE))
        functions = {{n.name for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}}
        classes = {{n.name for n in tree.body if isinstance(n, ast.ClassDef)}}
        self.assertTrue(set(EXPECTED_FUNCTIONS).issubset(functions))
        self.assertTrue(set(EXPECTED_CLASSES).issubset(classes))

    def test_source_file_exists_and_is_utf8(self):
        self.assertTrue(SOURCE.is_file())
        SOURCE.read_text(encoding="utf-8")
'''


class TestGenerator:
    """Generate and execute isolated, deterministic source-contract tests."""

    def __init__(self, root: str | Path):
        self.root = Path(root).expanduser().resolve()
        if not self.root.is_dir():
            raise TestGenerationError("project root does not exist")
        self.generated_dir = self.root / "tests" / "generated"

    def plan(self, changed_only: bool = False, base_ref: str = "HEAD^") -> GenerationReport:
        language, framework = detect_framework(self.root)
        report = GenerationReport(language == "python", language, framework)
        if not report.supported:
            report.skipped.append("no supported Python project detected")
            return report
        report.sources = discover_sources(self.root, changed_only=changed_only, base_ref=base_ref)
        if not report.sources:
            report.skipped.append("no eligible Python source files found")
        return report

    def generate(self, changed_only: bool = False, base_ref: str = "HEAD^") -> GenerationReport:
        report = self.plan(changed_only, base_ref)
        if not report.supported:
            return report
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        for source in report.sources:
            destination = self.generated_dir / f"{_test_name(source)}.py"
            destination.write_text(render_test(self.root, source), encoding="utf-8")
            report.generated.append(destination)
        return report

    def run(self, timeout: float = DEFAULT_TIMEOUT) -> dict[str, object]:
        timeout = float(timeout)
        if timeout <= 0 or timeout > MAX_TIMEOUT:
            raise TestGenerationError(f"timeout must be between 0 and {MAX_TIMEOUT} seconds")
        if not self.generated_dir.is_dir():
            return {"ok": False, "error": "no generated tests; run testgen generate first"}
        result = run_process(
            ["python", "-m", "unittest", "discover", "-s", str(self.generated_dir), "-p", "test_*.py"],
            cwd=self.root,
            timeout=timeout,
        )
        result["generated"] = True
        result["test_directory"] = str(self.generated_dir)
        return result

    def report(self, changed_only: bool = False, base_ref: str = "HEAD^") -> dict[str, object]:
        return self.plan(changed_only, base_ref).as_dict()
